// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJoucYvcx1yVLymoHl6MFPH2l9a6w6mR4',
    appId: '1:774798944751:web:22273f9198d9b373832e1a',
    messagingSenderId: '774798944751',
    projectId: 'car-help-d28f6',
    authDomain: 'car-help-d28f6.firebaseapp.com',
    storageBucket: 'car-help-d28f6.appspot.com',
    measurementId: 'G-46FW9TG415',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2kZ0hih8rhTKcE_mZ-6itgA9f0RFKqhA',
    appId: '1:774798944751:android:f659a5ffa75957eb832e1a',
    messagingSenderId: '774798944751',
    projectId: 'car-help-d28f6',
    storageBucket: 'car-help-d28f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMsWo61ZNrb4x5GO6bHpoaQUC4NUvYhs',
    appId: '1:774798944751:ios:90d9ac9a3d7c15e8832e1a',
    messagingSenderId: '774798944751',
    projectId: 'car-help-d28f6',
    storageBucket: 'car-help-d28f6.appspot.com',
    iosBundleId: 'com.carhelp.bundleId',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMsWo61ZNrb4x5GO6bHpoaQUC4NUvYhs',
    appId: '1:774798944751:ios:b4b4abc952087577832e1a',
    messagingSenderId: '774798944751',
    projectId: 'car-help-d28f6',
    storageBucket: 'car-help-d28f6.appspot.com',
    iosBundleId: 'com.example.carHelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJoucYvcx1yVLymoHl6MFPH2l9a6w6mR4',
    appId: '1:774798944751:web:f2ff6e3065967235832e1a',
    messagingSenderId: '774798944751',
    projectId: 'car-help-d28f6',
    authDomain: 'car-help-d28f6.firebaseapp.com',
    storageBucket: 'car-help-d28f6.appspot.com',
    measurementId: 'G-52C9DRC6YH',
  );
}
